DROP TABLE movie if EXISTS;
DROP TABLE movie_producers if EXISTS;
DROP TABLE movie_studios if EXISTS;
DROP TABLE producer if EXISTS;
DROP TABLE studio if EXISTS;
DROP VIEW prize_range if EXISTS;

    CREATE TABLE movie (
       id bigint generated by default as identity,
        title varchar(255),
        winner boolean not null,
        year integer not null,
        primary key (id)
    );

    CREATE TABLE movie_producers (
       producer_id bigint not null,
        movie_id bigint not null
    );

    
    CREATE TABLE movie_studios (
       movie_id bigint not null,
        studio_id bigint not null
    );

    
    CREATE TABLE producer (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    
    CREATE TABLE studio (
       id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    
    alter TABLE movie_producers 
       add constraint fk_movie_producers_movie 
       foreign key (movie_id) 
       references movie;

    
    alter TABLE movie_producers 
       add constraint fk_movie_producers_producer 
       foreign key (producer_id) 
       references producer;

    
    alter TABLE movie_studios 
       add constraint fk_movie_studios_studio 
       foreign key (studio_id) 
       references studio;

    
    alter TABLE movie_studios 
       add constraint fk_movie_studios_movie
       foreign key (movie_id) 
       references movie;
       
	CREATE force view prize_range as
	    SELECT ROWNUM() as ID,
	    	   tmp.producer_id                   AS PRODUCER_ID,
	           MIN(tmp.year)                     AS PREVIOUS_WIN,
	           MAX(tmp.year)                     AS FOLLOWING_WIN,
	           ( MAX(tmp.year) - MIN(tmp.year) ) AS "INTERVAL"
	    FROM   (SELECT p.id   AS producer_id,
	                   m.year AS year
	            FROM   producer p
	                   JOIN movie_producers mp
	                     ON ( p.id = mp.producer_id )
	                   JOIN movie m
	                     ON ( m.id = mp.movie_id )
	            WHERE  m.winner = TRUE) tmp
	    GROUP  BY tmp.producer_id;